
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: money_lending_system_development

test:
  <<: *default
  database: money_lending_system_test

production:
  <<: *default
  database: money_lending_system_production
  username: money_lending_system
  password: <%= ENV["MONEY_LENDING_SYSTEM_DATABASE_PASSWORD"] %>
